services:
  php:
    build: ./PHP
    ports:
      - "8080:80" #-> external 8080, internal 80
    volumes:
      - ../:/var/www/html
    depends_on:
      - mysql

  mysql:
    build: ./MySQL
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    args:
      uid : ${UID}
    env_file:
      - ./MySQL/.env

volumes:
  mysql_data: